export const countries = [
    { _id: "AF", title: "Afghanistan" },
    { _id: "AL", title: "Albania" },
    { _id: "DZ", title: "Algeria" },
    { _id: "AD", title: "Andorra" },
    { _id: "AO", title: "Angola" },
    { _id: "AR", title: "Argentina" },
    { _id: "AM", title: "Armenia" },
    { _id: "AU", title: "Australia" },
    { _id: "AT", title: "Austria" },
    { _id: "AZ", title: "Azerbaijan" },
    { _id: "BH", title: "Bahrain" },
    { _id: "BD", title: "Bangladesh" },
    { _id: "BY", title: "Belarus" },
    { _id: "BE", title: "Belgium" },
    { _id: "BZ", title: "Belize" },
    { _id: "BJ", title: "Benin" },
    { _id: "BT", title: "Bhutan" },
    { _id: "BO", title: "Bolivia" },
    { _id: "BA", title: "Bosnia and Herzegovina" },
    { _id: "BW", title: "Botswana" },
    { _id: "BR", title: "Brazil" },
    { _id: "BN", title: "Brunei" },
    { _id: "BG", title: "Bulgaria" },
    { _id: "BF", title: "Burkina Faso" },
    { _id: "BI", title: "Burundi" },
    { _id: "KH", title: "Cambodia" },
    { _id: "CM", title: "Cameroon" },
    { _id: "CA", title: "Canada" },
    { _id: "CV", title: "Cape Verde" },
    { _id: "CF", title: "Central African Republic" },
    { _id: "TD", title: "Chad" },
    { _id: "CL", title: "Chile" },
    { _id: "CN", title: "China" },
    { _id: "CO", title: "Colombia" },
    { _id: "KM", title: "Comoros" },
    { _id: "CG", title: "Congo" },
    { _id: "CR", title: "Costa Rica" },
    { _id: "HR", title: "Croatia" },
    { _id: "CU", title: "Cuba" },
    { _id: "CY", title: "Cyprus" },
    { _id: "CZ", title: "Czech Republic" },
    { _id: "DK", title: "Denmark" },
    { _id: "DJ", title: "Djibouti" },
    { _id: "DO", title: "Dominican Republic" },
    { _id: "EC", title: "Ecuador" },
    { _id: "EG", title: "Egypt" },
    { _id: "SV", title: "El Salvador" },
    { _id: "EE", title: "Estonia" },
    { _id: "ET", title: "Ethiopia" },
    { _id: "FI", title: "Finland" },
    { _id: "FR", title: "France" },
    { _id: "DE", title: "Germany" },
    { _id: "GH", title: "Ghana" },
    { _id: "GR", title: "Greece" },
    { _id: "GT", title: "Guatemala" },
    { _id: "GN", title: "Guinea" },
    { _id: "GY", title: "Guyana" },
    { _id: "HT", title: "Haiti" },
    { _id: "HN", title: "Honduras" },
    { _id: "HK", title: "Hong Kong" },
    { _id: "HU", title: "Hungary" },
    { _id: "IS", title: "Iceland" },
    { _id: "IN", title: "India" },
    { _id: "ID", title: "Indonesia" },
    { _id: "IR", title: "Iran" },
    { _id: "IQ", title: "Iraq" },
    { _id: "IE", title: "Ireland" },
    { _id: "IL", title: "Israel" },
    { _id: "IT", title: "Italy" },
    { _id: "JP", title: "Japan" },
    { _id: "JO", title: "Jordan" },
    { _id: "KZ", title: "Kazakhstan" },
    { _id: "KE", title: "Kenya" },
    { _id: "KR", title: "South Korea" },
    { _id: "KW", title: "Kuwait" },
    { _id: "LA", title: "Laos" },
    { _id: "LV", title: "Latvia" },
    { _id: "LB", title: "Lebanon" },
    { _id: "LY", title: "Libya" },
    { _id: "LT", title: "Lithuania" },
    { _id: "LU", title: "Luxembourg" },
    { _id: "MG", title: "Madagascar" },
    { _id: "MW", title: "Malawi" },
    { _id: "MY", title: "Malaysia" },
    { _id: "MV", title: "Maldives" },
    { _id: "ML", title: "Mali" },
    { _id: "MT", title: "Malta" },
    { _id: "MX", title: "Mexico" },
    { _id: "MD", title: "Moldova" },
    { _id: "MC", title: "Monaco" },
    { _id: "MN", title: "Mongolia" },
    { _id: "MA", title: "Morocco" },
    { _id: "MZ", title: "Mozambique" },
    { _id: "MM", title: "Myanmar" },
    { _id: "NA", title: "Namibia" },
    { _id: "NP", title: "Nepal" },
    { _id: "NL", title: "Netherlands" },
    { _id: "NZ", title: "New Zealand" },
    { _id: "NI", title: "Nicaragua" },
    { _id: "NE", title: "Niger" },
    { _id: "NG", title: "Nigeria" },
    { _id: "NO", title: "Norway" },
    { _id: "OM", title: "Oman" },
    { _id: "PK", title: "Pakistan" },
    { _id: "PA", title: "Panama" },
    { _id: "PY", title: "Paraguay" },
    { _id: "PE", title: "Peru" },
    { _id: "PH", title: "Philippines" },
    { _id: "PL", title: "Poland" },
    { _id: "PT", title: "Portugal" },
    { _id: "QA", title: "Qatar" },
    { _id: "RO", title: "Romania" },
    { _id: "RU", title: "Russia" },
    { _id: "SA", title: "Saudi Arabia" },
    { _id: "RS", title: "Serbia" },
    { _id: "SG", title: "Singapore" },
    { _id: "SK", title: "Slovakia" },
    { _id: "SI", title: "Slovenia" },
    { _id: "ZA", title: "South Africa" },
    { _id: "ES", title: "Spain" },
    { _id: "LK", title: "Sri Lanka" },
    { _id: "SE", title: "Sweden" },
    { _id: "CH", title: "Switzerland" },
    { _id: "SY", title: "Syria" },
    { _id: "TW", title: "Taiwan" },
    { _id: "TH", title: "Thailand" },
    { _id: "TN", title: "Tunisia" },
    { _id: "TR", title: "Turkey" },
    { _id: "UA", title: "Ukraine" },
    { _id: "AE", title: "United Arab Emirates" },
    { _id: "GB", title: "United Kingdom" },
    { _id: "US", title: "United States" },
    { _id: "UY", title: "Uruguay" },
    { _id: "UZ", title: "Uzbekistan" },
    { _id: "VE", title: "Venezuela" },
    { _id: "VN", title: "Vietnam" },
    { _id: "YE", title: "Yemen" },
    { _id: "ZM", title: "Zambia" },
    { _id: "ZW", title: "Zimbabwe" },
];
